let fonts = [
    'Blackadder ITC',
    'Agency FB',
    'Bauhaus 93',
    'Bradley Hand ITC',
    'Broadway',
    'Bodoni MT Poster Compressed',
    'Castellar',
    'Chiller',
    'Comic Sans MS',
    'Curlz MT',
    'Brush Script MT',
    'Edwardian Script ITC',
    'Footlight MT Light',
    'Freestyle Script',
    'French Script MT',
    'Gigi',
    'Forte',
    'Gill Sans MT Ext Condensed Bold',
    'Haettenschweiler',
    'Informal Roman',
    'Ink Free',
    'Jokerman',
    'Juice ITC',
    'Kunstler Script',
    'Liberation Mono',
    'Magneto',
    'Matura MT Script Capitals',
    'Mistral',
    'Vladimir Script',
    'Vivaldi',
    'Stencil',
    'Playbill',
    'American Typewriter',
    'Andale Mono',
    'Arial',
    'Arial Black',
    'Arial Narrow',
    'Arial Rounded MT Bold',
    'Arial Unicode MS',
    'Avenir',
    'Avenir Next',
    'Avenir Next Condensed',
    'Baskerville',
    'Big Caslon',
    'Bodoni 72',
    'Bodoni 72 Oldstyle',
    'Bodoni 72 Smallcaps',
    'Bradley Hand',
    'Brush Script MT',
    'Chalkboard',
    'Chalkboard SE',
    'Chalkduster',
    'Charter',
    'Cochin',
    'Comic Sans MS',
    'Copperplate',
    'Courier',
    'Courier New',
    'Didot',
    'DIN Alternate',
    'DIN Condensed',
    'Futura',
    'Garamond',
    'Geneva',
    'Georgia',
    'Gill Sans',
    'Helvetica',
    'Helvetica Neue',
    'Herculanum',
    'Hoefler Text',
    'Impact',
    'Lucida Grande',
    'Lucida Console',
    'Lucida Handwriting',
    'Luminari',
    'Marker Felt',
    'Menlo',
    'Microsoft Sans Serif',
    'Monaco',
    'Noteworthy',
    'Optima',
    'Palatino',
    'Papyrus',
    'Phosphate',
    'Rockwell',
    'Savoye LET',
    'SignPainter',
    'Skia',
    'Snell Roundhand',
    'Tahoma',
    'Times',
    'Times New Roman',
    'Trattatello',
    'Trebuchet MS',
    'Verdana',
    'Zapfino'
];